#!/usr/bin/env python
# -*- coding: utf-8 -*-

import requests
import html


try:
    req = requests.get("https://wtfismyip.com/json")
    ip_addr = req.json()['YourFuckingIPAddress']
    ip_isp  = html.unescape(req.json()['YourFuckingISP'])
    print(ip_addr + " (" + ip_isp + ")")
except Exception as e:
    print(":(")
