#!/usr/bin/env python
# -*- coding: utf-8 -*-

import requests

CITY = "2656192"
API_KEY = "55773ecd534deed83675063719d57459"
UNITS = "Metric"
UNIT_KEY = "C"

try:
    REQ = requests.get("http://api.openweathermap.org/data/2.5/weather?id={}&appid={}&units={}".format(CITY, API_KEY, UNITS))
    # HTTP CODE = OK
    if REQ.status_code == 200:
        CURRENT = REQ.json()["weather"][0]["description"].capitalize()
        TEMP = int(float(REQ.json()["main"]["temp"]))
        print("{}, {} °{}".format(CURRENT, TEMP, UNIT_KEY))
    else:
        print("Error: " + str(REQ.status_code))
except Exception as e:
    print(":(")
